parameters:
#    neko_to_neko_main.example.class: NekoToNeko\MainBundle\Example

services:
#    neko_to_neko_main.example:
#        class: %neko_to_neko_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
