fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    
nekotoneko_oauth_server_security:
    resource: "@NekoToNekoApiBundle/Resources/config/routing/security.xml"
    prefix: /
    
    
nekotoneko_test:
    defaults:  { _controller: NekoToNekoApiBundle:Default:coucou }
    pattern: /api/coucou